version: "3"
services:
  backend-server:
    container_name: easyca-dockertest-server
    build: 
      context: . 
      dockerfile: dockerfiles/Dockerfile.server
    ports:
      - "10443:443"
  server:
    container_name: easyca-dockertest-proxy
    build: 
      context: . 
      dockerfile: dockerfiles/Dockerfile.proxy
    ports:
      - "8080:80"
